### PR TITLE
Adapt rules

### PR DESCRIPTION
**Pull request by aaronspring**

### CODE REVIEW

**Comment by aaronspring** [comment]
Submissions methods should have sections how they check against overfitting. 

On reproducibility : from A -> Z

**Comment by awrobertson** [comment]
Possible text:
Submissions must include the forecasts obtained from the training period used, as well for the 2020 test period. The codes used must be fully documented, with details of the safeguards enacted to prevent overfitting. The organizers reserve the right to disqualify submissions if overfitting is suspected. [Can we require the codes upon submission? I don't think we can have a public leaderboard if we don't do that, but people may be afraid that we could miss-use them. There may be no option but to hide the leaderboard, or give the option of showing some other stats there, like performance on the training period, unranked - listed in order of submission.]

**Comment by aaronspring** [comment]
>  I don't think we can have a public leaderboard if we don't do that, but people may be afraid that we could miss-use them.

Technically, renku will require read access to their repos for the scorer. And I will have a password for that (renku could always generate a password). But no person will look into these.

> public leaderboard

I like the idea of having a non-public leaderboard now more and more. If people overfit, they will not know whether they are far above the others which do not overfit. If they are, we might expect overfitting and can maybe catch them once we see the code. If everybody is heavily overfitting this wont work.

> details of the safeguards enacted to prevent overfitting

I think I will provide a template notebook where in the header we will have the following documentation sections to fill:
- resources: what machine did you do the training on? CPUs, memory, nodes
- safeguards to prevent [overfitting](https://en.wikipedia.org/wiki/Overfitting?wprov=sfti1): (If we suspect any of these, no prize)
  - [ ] We didnt use 2020 observations in training (explicit overfitting and cheating)
  - [ ] We didnt repeatedly verify my model on 2020 observations and incrementally improved my RPSS (implicit overfitting)
  - [ ] We tried our best to prevent [data leakage](https://en.wikipedia.org/wiki/Leakage_(machine_learning)?wprov=sfti1).
- safeguards for reproducibility: Notebook/code must be independently reproducible from scratch by the organizers (after the competition), if not possible: no prize
     - [ ] all training data is publicly available (no pre-trained private neural networks, as they are not reproducible for us)
     - [ ] code is well documented
     - [ ] code runs in a reasonable amount of time (within a day?)

**Comment by aaronspring** [comment]
Add figure of inputs and outputs of ML model and how forecasts can be predicted

**Comment by aaronspring** [comment]
Maybe add https://library.wmo.int/doc_num.php?explnum_id=10314

**Comment by aaronspring** [comment]
> Submissions must include the forecasts obtained from the training period used, as well for the 2020 test period. 

Nice to know but how does this prevent overfitting? I only shows that the training data is maybe not overfitted.

**Review by FredericVitart — COMMENTED** [review]
Looks fine to me. Just noticed a typo: line 44: "why could cannot" should be "why you cannot"

**Comment by aaronspring** [comment]
I will wait for the confirmation of the timeline by email.

**Pull request merged**
